### PR TITLE
Add script: runHostTestsCsv.sh as an auxiliary output option

### PR DESCRIPTION
**Pull request by TaEduard**
Add script: runHostTestsCsv.sh as an auxiliary output option that creates a csv report of the findings.

### CODE REVIEW

**Comment by konstruktoid** [comment]
Hi and thank you @TaEduard!
Could you take a look at https://github.com/konstruktoid/hardening/actions/runs/8235352666/job/22536038419?pr=391#step:5:47?

**Review by konstruktoid — COMMENTED** [review]
https://github.com/konstruktoid/hardening/actions/runs/8235352666/job/22536038419?pr=391#step:5:47

**Comment by TaEduard** [comment]
Hello, 
I think now everything should be fine, I've ran locally `shellcheck` to ensure we're not hitting another similar situation.

**Review by konstruktoid — APPROVED** [review]

**Comment by konstruktoid** [comment]
Thanks @TaEduard!

**Pull request merged**
