### PR TITLE
package manager agnostic test

### PR DESCRIPTION
**Pull request by gcb**

### CODE REVIEW

**Comment by konstruktoid** [comment]
Hi, the reason is that installation of firewall (CIS: `3.5.1.1 Ensure a Firewall package is installed`) is separate from  the policy setting (CIS: `3.5.2.2 Ensure default deny firewall policy`).

**Comment by gcb** [comment]
the test will also fail if the binary is not present (i.e. not installed) but the test can now be used on distros without that specific package manager (not sure if that is a goal, but i'm using some files from this repo on other distros)

**Comment by konstruktoid** [comment]
True.

On which distributions are you using the scripts and tests?
It's made for Ubuntu, and I haven't tested this repo on any other distros, using the Ansible repo for that.

**Comment by gcb** [comment]
i am transitioning from ubuntu to a mix of arch for my server/desktops and openbsd for the mobile laptops.

i will take a look on the ansible one. but i liked this solution being bash only.

**Comment by konstruktoid** [comment]
Cool, but which other distros use `ufw`?

**Comment by gcb** [comment]
Arch. https://wiki.archlinux.org/index.php/Uncomplicated_Firewall#Installation

also took another look at why i disregarded the ansible repo before :) it was probably yaml. can't stand the thing.

**Comment by konstruktoid** [comment]
Thanks!

Too each his own, but coming from Puppet and its ruby(ish) configuration, yaml is awesome ;)

**Pull request merged**
