### PR TITLE
[Upgrade] sysctl.conf - More Kernel Hardening

### PR DESCRIPTION
**Pull request by hellresistor**
maybe need adjustments on values to your needs!!

### CODE REVIEW

**Comment by konstruktoid** [comment]
Thanks, but do you got any documentation or references regarding this?

**Comment by hellresistor** [comment]
> Thanks, but do you got any documentation or references regarding this?

To each command i have read info (not same website (some info on red hat other info on kernel... etc) , BUT, some values need adjustments because of services types of server and hardware specs.

**Comment by konstruktoid** [comment]
Yeah, but I want some security related references regarding these changes.
he remote host implements TCP timestamps and therefore allows to compute
the uptime (http://www.securityspace.com/smysecure/catid.html?id=1.3.6.1.4.1.25623.1.0.80091 among others).

**Comment by hellresistor** [comment]
Ohh jiizzz.. THANK YOU! i have changed that mistaken!

**Comment by konstruktoid** [comment]
But what are the reasons for the rest? They seem to be more like performance related settings.

**Comment by hellresistor** [comment]
I will comment each block to better understand.. but later. not today or tomorrow... sorry

**Comment by konstruktoid** [comment]
Will close soon due to inactivity.

**Comment by hellresistor** [comment]
to be continued..

**Pull request closed without merging**
